/**
 * Template Registry — the single source of truth for all resume templates.
 *
 * Templates are lazy-loaded via React.lazy() to keep the initial bundle small.
 * The registry is keyed by template ID (matches the DB templateId column).
 *
 * Adding a new template:
 *   1. Create src/templates/<id>/index.tsx
 *   2. Add an entry here
 *   3. Done — no other changes needed
 */

import { lazy } from 'react'
import type { TemplateRegistry } from '@/types/template'

export const templateRegistry: TemplateRegistry = {
  'classic-professional': {
    id: 'classic-professional',
    name: 'Classic Professional',
    description: 'A timeless, ATS-optimized single-column layout trusted by Fortune 500 recruiters.',
    category: 'professional',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('classic-professional'),
    tags: ['ats-friendly', 'single-column', 'traditional'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: false,
    createdAt: '2024-01-01',
    component: lazy(() => import('./classic-professional')),
  },
  'modern-minimal': {
    id: 'modern-minimal',
    name: 'Modern Minimal',
    description: 'Clean, contemporary design with an accent sidebar. Perfect for tech roles.',
    category: 'modern',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('modern-minimal'),
    tags: ['modern', 'sidebar', 'tech'],
    isAtsOptimized: true,
    supportsAvatar: true,
    supportsTwoColumns: true,
    createdAt: '2024-01-01',
    component: lazy(() => import('./modern-minimal')),
  },
  'minimal-clean': {
    id: 'minimal-clean',
    name: 'Minimal Clean',
    description: 'Ultra-clean whitespace-driven design. Less is more.',
    category: 'minimal',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('minimal-clean'),
    tags: ['minimal', 'whitespace', 'clean'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: false,
    createdAt: '2024-01-01',
    component: lazy(() => import('./minimal-clean')),
  },
  'modern-vanguard': {
    id: 'modern-vanguard',
    name: 'Modern Vanguard',
    description: 'Centered header with elegant, letter-spaced typography and clean divider rules.',
    category: 'modern',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('modern-vanguard'),
    tags: ['modern', 'centered', 'elegant'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: false,
    createdAt: '2024-01-01',
    component: lazy(() => import('./modern-vanguard')),
  },
  'modern-sidebar': {
    id: 'modern-sidebar',
    name: 'Modern Sidebar',
    description: 'Compact tinted sidebar with a spacious, single-column content area.',
    category: 'modern',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('modern-sidebar'),
    tags: ['modern', 'sidebar', 'spacious'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: true,
    createdAt: '2024-01-01',
    component: lazy(() => import('./modern-sidebar')),
  },
  'modern-split': {
    id: 'modern-split',
    name: 'Modern Split',
    description: 'Full-width accent header over a balanced two-column body with a divider rail.',
    category: 'modern',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('modern-split'),
    tags: ['modern', 'two-column', 'header'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: true,
    createdAt: '2024-01-01',
    component: lazy(() => import('./modern-split')),
  },
  'modern-timeline': {
    id: 'modern-timeline',
    name: 'Modern Timeline',
    description: 'Minimal contact row and a soft-accent experience timeline for clear hierarchy.',
    category: 'modern',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('modern-timeline'),
    tags: ['modern', 'timeline', 'soft-accent'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: false,
    createdAt: '2024-01-01',
    component: lazy(() => import('./modern-timeline')),
  },
  'modern-grid': {
    id: 'modern-grid',
    name: 'Modern Grid',
    description: 'Grid-based alignment with modern lowercase-spaced headings and crisp structure.',
    category: 'modern',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('modern-grid'),
    tags: ['modern', 'grid', 'structured'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: true,
    createdAt: '2024-01-01',
    component: lazy(() => import('./modern-grid')),
  },
  'professional-edge': {
    id: 'professional-edge',
    name: 'Edge',
    description: 'Full-width elegant header with a serif name and strong single-column dividers.',
    category: 'professional',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('professional-edge'),
    tags: ['professional', 'header', 'single-column'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: false,
    createdAt: '2024-01-01',
    component: lazy(() => import('./professional-edge')),
  },
  'professional-meridian': {
    id: 'professional-meridian',
    name: 'Meridian',
    description: 'Slim left rail with competencies and a wide experience-led content column.',
    category: 'professional',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('professional-meridian'),
    tags: ['professional', 'sidebar', 'business'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: true,
    createdAt: '2024-01-01',
    component: lazy(() => import('./professional-meridian')),
  },
  'professional-atlas': {
    id: 'professional-atlas',
    name: 'Atlas',
    description: 'Centered serif name, contact bar, and a balanced two-column body.',
    category: 'professional',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('professional-atlas'),
    tags: ['professional', 'centered', 'two-column'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: true,
    createdAt: '2024-01-01',
    component: lazy(() => import('./professional-atlas')),
  },
  'professional-pinnacle': {
    id: 'professional-pinnacle',
    name: 'Pinnacle',
    description: 'Compact header, timeline experience, and bold uppercase headings.',
    category: 'professional',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('professional-pinnacle'),
    tags: ['professional', 'timeline', 'enterprise'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: false,
    createdAt: '2024-01-01',
    component: lazy(() => import('./professional-pinnacle')),
  },
  'professional-cadence': {
    id: 'professional-cadence',
    name: 'Cadence',
    description: 'Grid-based sections with accent top-borders and elegant whitespace.',
    category: 'professional',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('professional-cadence'),
    tags: ['professional', 'grid', 'corporate'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: true,
    createdAt: '2024-01-01',
    component: lazy(() => import('./professional-cadence')),
  },
  'minimal-whitespace': {
    id: 'minimal-whitespace',
    name: 'Minimal Whitespace',
    description: 'Centered light-weight name with a hairline rule and an airy, whitespace-driven single column.',
    category: 'minimal',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('minimal-whitespace'),
    tags: ['minimal', 'centered', 'whitespace'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: false,
    createdAt: '2024-01-01',
    component: lazy(() => import('./minimal-whitespace')),
  },
  'minimal-editorial': {
    id: 'minimal-editorial',
    name: 'Minimal Editorial',
    description: 'Left-anchored serif name with a vertical accent rule and spacious single-column body.',
    category: 'minimal',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('minimal-editorial'),
    tags: ['minimal', 'editorial', 'serif'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: false,
    createdAt: '2024-01-01',
    component: lazy(() => import('./minimal-editorial')),
  },
  'minimal-asymmetric': {
    id: 'minimal-asymmetric',
    name: 'Minimal Asymmetric',
    description: 'Compact header over a balanced two-column body — experience left, supporting details right.',
    category: 'minimal',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('minimal-asymmetric'),
    tags: ['minimal', 'two-column', 'balanced'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: true,
    createdAt: '2024-01-01',
    component: lazy(() => import('./minimal-asymmetric')),
  },
  'minimal-chronicle': {
    id: 'minimal-chronicle',
    name: 'Minimal Chronicle',
    description: 'Soft-gray header band with a quiet chronological experience timeline and clean full-width rules.',
    category: 'minimal',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('minimal-chronicle'),
    tags: ['minimal', 'timeline', 'soft-accent'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: false,
    createdAt: '2024-01-01',
    component: lazy(() => import('./minimal-chronicle')),
  },
  'minimal-portfolio': {
    id: 'minimal-portfolio',
    name: 'Minimal Portfolio',
    description: 'Compact header and a refined two-column grid of small-caps section blocks with premium whitespace.',
    category: 'minimal',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('minimal-portfolio'),
    tags: ['minimal', 'grid', 'index'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: true,
    createdAt: '2024-01-01',
    component: lazy(() => import('./minimal-portfolio')),
  },

  // ── Creative Templates ─────────────────────────────────────────────────────

  'creative-portfolio': {
    id: 'creative-portfolio',
    name: 'Modern Portfolio',
    description: 'Bold large-scale header with editorial two-column rhythm — a design portfolio table of contents.',
    category: 'creative',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('creative-portfolio'),
    tags: ['creative', 'editorial', 'two-column'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: true,
    createdAt: '2025-06-01',
    component: lazy(() => import('./creative-portfolio')),
  },
  'creative-accent': {
    id: 'creative-accent',
    name: 'Color Accent',
    description: 'Clean white canvas with bold accent-colored section header bands. Minimal, striking, organized.',
    category: 'creative',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('creative-accent'),
    tags: ['creative', 'accent', 'single-column'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: false,
    createdAt: '2025-06-01',
    component: lazy(() => import('./creative-accent')),
  },
  'creative-magazine': {
    id: 'creative-magazine',
    name: 'Magazine Style',
    description: 'Editorial layout with serif name, italic headline, and dynamic multi-column grid sections.',
    category: 'creative',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('creative-magazine'),
    tags: ['creative', 'magazine', 'editorial', 'multi-column'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: true,
    createdAt: '2025-06-01',
    component: lazy(() => import('./creative-magazine')),
  },
  'creative-designer': {
    id: 'creative-designer',
    name: 'Elegant Designer',
    description: 'Compact header, tinted side panel with skills/languages, and a spacious main content column.',
    category: 'creative',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('creative-designer'),
    tags: ['creative', 'sidebar', 'elegant', 'two-column'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: true,
    createdAt: '2025-06-01',
    component: lazy(() => import('./creative-designer')),
  },
  'creative-modern': {
    id: 'creative-modern',
    name: 'Creative Professional',
    description: 'Card grid with accent left-borders, compact top header, and soft background — structured and modern.',
    category: 'creative',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('creative-modern'),
    tags: ['creative', 'cards', 'grid', 'modern'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: true,
    createdAt: '2025-06-01',
    component: lazy(() => import('./creative-modern')),
  },

  // ── Technology Templates ──────────────────────────────────────────────────

  'tech-architect': {
    id: 'tech-architect',
    name: 'Software Engineer',
    description: 'Stacked bordered panels with corner accent tabs. Clean header with full contact row. Two-column skill grid with bordered pill tags. Professional systems-engineer aesthetic.',
    category: 'technology',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('tech-architect'),
    tags: ['technology', 'panels', 'stacked', 'systems'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: false,
    createdAt: '2025-07-21',
    component: lazy(() => import('./tech-architect')),
  },
  'tech-fullstack': {
    id: 'tech-fullstack',
    name: 'Full Stack Developer',
    description: 'Full-height accent left rail with hanging section titles. Date badges in experience, dot-prefixed skills in a three-column grid. Modern developer portfolio feel.',
    category: 'technology',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('tech-fullstack'),
    tags: ['technology', 'left-rail', 'badges', 'fullstack'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: false,
    createdAt: '2025-07-21',
    component: lazy(() => import('./tech-fullstack')),
  },
  'tech-data-scientist': {
    id: 'tech-data-scientist',
    name: 'Data & AI Professional',
    description: 'Alternating section background tints create visual rhythm. Monospace company names in experience. Two-column bordered skill matrix cells. Clean, research-oriented layout.',
    category: 'technology',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('tech-data-scientist'),
    tags: ['technology', 'alternating', 'monospace', 'data'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: false,
    createdAt: '2025-07-21',
    component: lazy(() => import('./tech-data-scientist')),
  },
  'tech-cloud-engineering': {
    id: 'tech-cloud-engineering',
    name: 'DevOps & Cloud Engineer',
    description: 'Metrics stats bar below header. Accent-filled skill pill tags. Experience entries with a left accent border. Certification cards in a two-column grid. Corporate infrastructure feel.',
    category: 'technology',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('tech-cloud-engineering'),
    tags: ['technology', 'metrics', 'filled-pills', 'cert-grid'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: false,
    createdAt: '2025-07-21',
    component: lazy(() => import('./tech-cloud-engineering')),
  },
  'tech-product-designer': {
    id: 'tech-product-designer',
    name: 'UI/UX & Product Designer',
    description: 'Asymmetric two-column split (1.8:1) with no divider. Left column carries narrative sections. Right column holds skill groups in bordered boxes. Full-width project cards with left accent border.',
    category: 'technology',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('tech-product-designer'),
    tags: ['technology', 'asymmetric', 'project-cards', 'designer'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: true,
    createdAt: '2025-07-21',
    component: lazy(() => import('./tech-product-designer')),
  },
  // ── Business Templates ────────────────────────────────────────────────────

  'business-corporate-manager': {
    id: 'business-corporate-manager',
    name: 'Corporate Manager',
    description: 'Premium single-column with a full-width dark header band, executive summary call-out box, and structured experience entries with thin dividers. Designed for corporate managers, directors, and VPs.',
    category: 'business',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('business-corporate-manager'),
    tags: ['business', 'corporate', 'executive', 'single-column'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: false,
    createdAt: '2025-07-21',
    component: lazy(() => import('./business-corporate-manager')),
  },
  'business-consultant': {
    id: 'business-consultant',
    name: 'Business Consultant',
    description: 'Slim dark charcoal sidebar (28%) with contact, skills, and certifications. Clean white main area with dot-prefixed section titles. Ideal for management consultants, strategists, and analysts.',
    category: 'business',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('business-consultant'),
    tags: ['business', 'consulting', 'sidebar', 'two-column'],
    isAtsOptimized: true,
    supportsAvatar: true,
    supportsTwoColumns: true,
    createdAt: '2025-07-21',
    component: lazy(() => import('./business-consultant')),
  },
  'business-marketing-executive': {
    id: 'business-marketing-executive',
    name: 'Marketing Executive',
    description: 'Centered uppercase header with italic headline, two-column body (1.4:1 ratio), and soft warm section backgrounds. Perfect for CMOs, brand directors, and marketing leaders.',
    category: 'business',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('business-marketing-executive'),
    tags: ['business', 'marketing', 'two-column', 'centered'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: true,
    createdAt: '2025-07-21',
    component: lazy(() => import('./business-marketing-executive')),
  },
  'business-sales-leader': {
    id: 'business-sales-leader',
    name: 'Sales Leader',
    description: 'Timeline-based experience track with date badges and connecting dots. Card-style sections for awards and achievements. KPI-friendly layout for sales directors and revenue leaders.',
    category: 'business',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('business-sales-leader'),
    tags: ['business', 'sales', 'timeline', 'cards'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: false,
    createdAt: '2025-07-21',
    component: lazy(() => import('./business-sales-leader')),
  },
  'business-operations-director': {
    id: 'business-operations-director',
    name: 'Operations Director',
    description: 'Grid-based two-column layout with a leadership summary panel, accent-bordered experience entries, and numbered achievement badges. Geared toward COOs, ops directors, and supply chain leaders.',
    category: 'business',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('business-operations-director'),
    tags: ['business', 'operations', 'grid', 'two-column'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: true,
    createdAt: '2025-07-21',
    component: lazy(() => import('./business-operations-director')),
  },
}

export const DEFAULT_TEMPLATE_ID = 'classic-professional'

/**
 * Derived preview URL for a template. Mirrors the `template-previews` storage
 * bucket path (created by the DB migration) — drop a `<id>.png` there and the
 * template gains a real preview image with no code change.
 */
export function getTemplatePreviewUrl(id: string): string {
  return `/storage/v1/object/public/template-previews/${id}.png`
}

/** Returns the template list for the template browser */
export function getTemplateList() {
  return Object.values(templateRegistry)
}
