/**
 * Template Registry — the single source of truth for all resume templates.
 *
 * Templates are lazy-loaded via React.lazy() to keep the initial bundle small.
 * The registry is keyed by template ID (matches the DB templateId column).
 *
 * Adding a new template:
 *   1. Create src/templates/<id>/index.tsx
 *   2. Add an entry here
 *   3. Done — no other changes needed
 */

import { lazy } from 'react'
import type { TemplateRegistry } from '@/types/template'

export const templateRegistry: TemplateRegistry = {
  'classic-professional': {
    id: 'classic-professional',
    name: 'Classic Professional',
    description: 'A timeless, ATS-optimized single-column layout trusted by Fortune 500 recruiters.',
    category: 'professional',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('classic-professional'),
    tags: ['ats-friendly', 'single-column', 'traditional'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: false,
    createdAt: '2024-01-01',
    component: lazy(() => import('./classic-professional')),
  },
  'modern-minimal': {
    id: 'modern-minimal',
    name: 'Modern Minimal',
    description: 'Clean, contemporary design with an accent sidebar. Perfect for tech roles.',
    category: 'modern',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('modern-minimal'),
    tags: ['modern', 'sidebar', 'tech'],
    isAtsOptimized: true,
    supportsAvatar: true,
    supportsTwoColumns: true,
    createdAt: '2024-01-01',
    component: lazy(() => import('./modern-minimal')),
  },
  'minimal-clean': {
    id: 'minimal-clean',
    name: 'Minimal Clean',
    description: 'Ultra-clean whitespace-driven design. Less is more.',
    category: 'minimal',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('minimal-clean'),
    tags: ['minimal', 'whitespace', 'clean'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: false,
    createdAt: '2024-01-01',
    component: lazy(() => import('./minimal-clean')),
  },
  'modern-vanguard': {
    id: 'modern-vanguard',
    name: 'Modern Vanguard',
    description: 'Centered header with elegant, letter-spaced typography and clean divider rules.',
    category: 'modern',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('modern-vanguard'),
    tags: ['modern', 'centered', 'elegant'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: false,
    createdAt: '2024-01-01',
    component: lazy(() => import('./modern-vanguard')),
  },
  'modern-sidebar': {
    id: 'modern-sidebar',
    name: 'Modern Sidebar',
    description: 'Compact tinted sidebar with a spacious, single-column content area.',
    category: 'modern',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('modern-sidebar'),
    tags: ['modern', 'sidebar', 'spacious'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: true,
    createdAt: '2024-01-01',
    component: lazy(() => import('./modern-sidebar')),
  },
  'modern-split': {
    id: 'modern-split',
    name: 'Modern Split',
    description: 'Full-width accent header over a balanced two-column body with a divider rail.',
    category: 'modern',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('modern-split'),
    tags: ['modern', 'two-column', 'header'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: true,
    createdAt: '2024-01-01',
    component: lazy(() => import('./modern-split')),
  },
  'modern-timeline': {
    id: 'modern-timeline',
    name: 'Modern Timeline',
    description: 'Minimal contact row and a soft-accent experience timeline for clear hierarchy.',
    category: 'modern',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('modern-timeline'),
    tags: ['modern', 'timeline', 'soft-accent'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: false,
    createdAt: '2024-01-01',
    component: lazy(() => import('./modern-timeline')),
  },
  'modern-grid': {
    id: 'modern-grid',
    name: 'Modern Grid',
    description: 'Grid-based alignment with modern lowercase-spaced headings and crisp structure.',
    category: 'modern',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('modern-grid'),
    tags: ['modern', 'grid', 'structured'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: true,
    createdAt: '2024-01-01',
    component: lazy(() => import('./modern-grid')),
  },
  'professional-edge': {
    id: 'professional-edge',
    name: 'Edge',
    description: 'Full-width elegant header with a serif name and strong single-column dividers.',
    category: 'professional',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('professional-edge'),
    tags: ['professional', 'header', 'single-column'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: false,
    createdAt: '2024-01-01',
    component: lazy(() => import('./professional-edge')),
  },
  'professional-meridian': {
    id: 'professional-meridian',
    name: 'Meridian',
    description: 'Slim left rail with competencies and a wide experience-led content column.',
    category: 'professional',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('professional-meridian'),
    tags: ['professional', 'sidebar', 'business'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: true,
    createdAt: '2024-01-01',
    component: lazy(() => import('./professional-meridian')),
  },
  'professional-atlas': {
    id: 'professional-atlas',
    name: 'Atlas',
    description: 'Centered serif name, contact bar, and a balanced two-column body.',
    category: 'professional',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('professional-atlas'),
    tags: ['professional', 'centered', 'two-column'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: true,
    createdAt: '2024-01-01',
    component: lazy(() => import('./professional-atlas')),
  },
  'professional-pinnacle': {
    id: 'professional-pinnacle',
    name: 'Pinnacle',
    description: 'Compact header, timeline experience, and bold uppercase headings.',
    category: 'professional',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('professional-pinnacle'),
    tags: ['professional', 'timeline', 'enterprise'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: false,
    createdAt: '2024-01-01',
    component: lazy(() => import('./professional-pinnacle')),
  },
  'professional-cadence': {
    id: 'professional-cadence',
    name: 'Cadence',
    description: 'Grid-based sections with accent top-borders and elegant whitespace.',
    category: 'professional',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('professional-cadence'),
    tags: ['professional', 'grid', 'corporate'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: true,
    createdAt: '2024-01-01',
    component: lazy(() => import('./professional-cadence')),
  },
  'minimal-whitespace': {
    id: 'minimal-whitespace',
    name: 'Minimal Whitespace',
    description: 'Centered light-weight name with a hairline rule and an airy, whitespace-driven single column.',
    category: 'minimal',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('minimal-whitespace'),
    tags: ['minimal', 'centered', 'whitespace'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: false,
    createdAt: '2024-01-01',
    component: lazy(() => import('./minimal-whitespace')),
  },
  'minimal-editorial': {
    id: 'minimal-editorial',
    name: 'Minimal Editorial',
    description: 'Left-anchored serif name with a vertical accent rule and spacious single-column body.',
    category: 'minimal',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('minimal-editorial'),
    tags: ['minimal', 'editorial', 'serif'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: false,
    createdAt: '2024-01-01',
    component: lazy(() => import('./minimal-editorial')),
  },
  'minimal-asymmetric': {
    id: 'minimal-asymmetric',
    name: 'Minimal Asymmetric',
    description: 'Compact header over a balanced two-column body — experience left, supporting details right.',
    category: 'minimal',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('minimal-asymmetric'),
    tags: ['minimal', 'two-column', 'balanced'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: true,
    createdAt: '2024-01-01',
    component: lazy(() => import('./minimal-asymmetric')),
  },
  'minimal-chronicle': {
    id: 'minimal-chronicle',
    name: 'Minimal Chronicle',
    description: 'Soft-gray header band with a quiet chronological experience timeline and clean full-width rules.',
    category: 'minimal',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('minimal-chronicle'),
    tags: ['minimal', 'timeline', 'soft-accent'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: false,
    createdAt: '2024-01-01',
    component: lazy(() => import('./minimal-chronicle')),
  },
  'minimal-portfolio': {
    id: 'minimal-portfolio',
    name: 'Minimal Portfolio',
    description: 'Compact header and a refined two-column grid of small-caps section blocks with premium whitespace.',
    category: 'minimal',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('minimal-portfolio'),
    tags: ['minimal', 'grid', 'index'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: true,
    createdAt: '2024-01-01',
    component: lazy(() => import('./minimal-portfolio')),
  },

  // ── Creative Templates ─────────────────────────────────────────────────────

  'creative-portfolio': {
    id: 'creative-portfolio',
    name: 'Modern Portfolio',
    description: 'Bold large-scale header with editorial two-column rhythm — a design portfolio table of contents.',
    category: 'creative',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('creative-portfolio'),
    tags: ['creative', 'editorial', 'two-column'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: true,
    createdAt: '2025-06-01',
    component: lazy(() => import('./creative-portfolio')),
  },
  'creative-accent': {
    id: 'creative-accent',
    name: 'Color Accent',
    description: 'Clean white canvas with bold accent-colored section header bands. Minimal, striking, organized.',
    category: 'creative',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('creative-accent'),
    tags: ['creative', 'accent', 'single-column'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: false,
    createdAt: '2025-06-01',
    component: lazy(() => import('./creative-accent')),
  },
  'creative-magazine': {
    id: 'creative-magazine',
    name: 'Magazine Style',
    description: 'Editorial layout with serif name, italic headline, and dynamic multi-column grid sections.',
    category: 'creative',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('creative-magazine'),
    tags: ['creative', 'magazine', 'editorial', 'multi-column'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: true,
    createdAt: '2025-06-01',
    component: lazy(() => import('./creative-magazine')),
  },
  'creative-designer': {
    id: 'creative-designer',
    name: 'Elegant Designer',
    description: 'Compact header, tinted side panel with skills/languages, and a spacious main content column.',
    category: 'creative',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('creative-designer'),
    tags: ['creative', 'sidebar', 'elegant', 'two-column'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: true,
    createdAt: '2025-06-01',
    component: lazy(() => import('./creative-designer')),
  },
  'creative-modern': {
    id: 'creative-modern',
    name: 'Creative Professional',
    description: 'Card grid with accent left-borders, compact top header, and soft background — structured and modern.',
    category: 'creative',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('creative-modern'),
    tags: ['creative', 'cards', 'grid', 'modern'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: true,
    createdAt: '2025-06-01',
    component: lazy(() => import('./creative-modern')),
  },

  // ── Technology Templates ──────────────────────────────────────────────────

  'tech-architect': {
    id: 'tech-architect',
    name: 'Software Engineer',
    description: 'Stacked bordered panels with corner accent tabs. Clean header with full contact row. Two-column skill grid with bordered pill tags. Professional systems-engineer aesthetic.',
    category: 'technology',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('tech-architect'),
    tags: ['technology', 'panels', 'stacked', 'systems'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: false,
    createdAt: '2025-07-21',
    component: lazy(() => import('./tech-architect')),
  },
  'tech-fullstack': {
    id: 'tech-fullstack',
    name: 'Full Stack Developer',
    description: 'Full-height accent left rail with hanging section titles. Date badges in experience, dot-prefixed skills in a three-column grid. Modern developer portfolio feel.',
    category: 'technology',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('tech-fullstack'),
    tags: ['technology', 'left-rail', 'badges', 'fullstack'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: false,
    createdAt: '2025-07-21',
    component: lazy(() => import('./tech-fullstack')),
  },
  'tech-data-scientist': {
    id: 'tech-data-scientist',
    name: 'Data & AI Professional',
    description: 'Alternating section background tints create visual rhythm. Monospace company names in experience. Two-column bordered skill matrix cells. Clean, research-oriented layout.',
    category: 'technology',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('tech-data-scientist'),
    tags: ['technology', 'alternating', 'monospace', 'data'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: false,
    createdAt: '2025-07-21',
    component: lazy(() => import('./tech-data-scientist')),
  },
  'tech-cloud-engineering': {
    id: 'tech-cloud-engineering',
    name: 'DevOps & Cloud Engineer',
    description: 'Metrics stats bar below header. Accent-filled skill pill tags. Experience entries with a left accent border. Certification cards in a two-column grid. Corporate infrastructure feel.',
    category: 'technology',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('tech-cloud-engineering'),
    tags: ['technology', 'metrics', 'filled-pills', 'cert-grid'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: false,
    createdAt: '2025-07-21',
    component: lazy(() => import('./tech-cloud-engineering')),
  },
  'tech-product-designer': {
    id: 'tech-product-designer',
    name: 'UI/UX & Product Designer',
    description: 'Asymmetric two-column split (1.8:1) with no divider. Left column carries narrative sections. Right column holds skill groups in bordered boxes. Full-width project cards with left accent border.',
    category: 'technology',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('tech-product-designer'),
    tags: ['technology', 'asymmetric', 'project-cards', 'designer'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: true,
    createdAt: '2025-07-21',
    component: lazy(() => import('./tech-product-designer')),
  },
  // ── Business Templates ────────────────────────────────────────────────────

  'business-executive-suite': {
    id: 'business-executive-suite',
    name: 'Executive Suite',
    description: 'The only template with a right-aligned sidebar on a dark accent background. Name sits in the main (left) area. Section titles use a short accent left-border bar. Built for C-suite executives and board members.',
    category: 'business',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('business-executive-suite'),
    tags: ['business', 'executive', 'right-sidebar', 'c-suite'],
    isAtsOptimized: true,
    supportsAvatar: true,
    supportsTwoColumns: true,
    createdAt: '2025-07-21',
    component: lazy(() => import('./business-executive-suite')),
  },
  'business-diplomat': {
    id: 'business-diplomat',
    name: 'Diplomat',
    description: 'Thin accent-colored border frames the entire document like formal executive stationery. Letterhead-style header with decorative accent rule. Section labels sit beside a subtle gray line. For managing directors and senior advisors.',
    category: 'business',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('business-diplomat'),
    tags: ['business', 'framed', 'letterhead', 'stationery'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: false,
    createdAt: '2025-07-21',
    component: lazy(() => import('./business-diplomat')),
  },
  'business-capital': {
    id: 'business-capital',
    name: 'Capital',
    description: 'Editorial drop-cap initials — the first letter of each section heading is a large accent-colored initial, with the remainder in small uppercase. Two-end header with bold name left, contact right. For strategy and communications leaders.',
    category: 'business',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('business-capital'),
    tags: ['business', 'editorial', 'drop-cap', 'single-column'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: false,
    createdAt: '2025-07-21',
    component: lazy(() => import('./business-capital')),
  },
  'business-overlook': {
    id: 'business-overlook',
    name: 'Overlook',
    description: 'Top-dominant executive panel (~30% of page) on a dark accent background with name, headline, metric badges, and summary callout. Below is a two-column narrative. An executive briefing concept for CEOs and VPs.',
    category: 'business',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('business-overlook'),
    tags: ['business', 'executive', 'metrics', 'two-column'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: true,
    createdAt: '2025-07-21',
    component: lazy(() => import('./business-overlook')),
  },
  'business-tract': {
    id: 'business-tract',
    name: 'Tract',
    description: 'Alternating section banners with floating accent-colored pill titles. Experience entries have a left accent flag border. Skills as bordered tags. A modern structured-report feel for operations directors and program managers.',
    category: 'business',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('business-tract'),
    tags: ['business', 'banners', 'alternating', 'single-column'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: false,
    createdAt: '2025-07-21',
    component: lazy(() => import('./business-tract')),
  },

  // ── Finance Templates ─────────────────────────────────────────────────────

  'finance-ledger': {
    id: 'finance-ledger',
    name: 'Ledger',
    description: 'A balance-sheet-inspired layout with three horizontal bands. Thin dark-accent header strip, 2:1 left-heavy column split with proportional skill "asset allocation" bars, and a compact footer for achievements. For CFOs, FP&A leaders, and accounting executives.',
    category: 'finance',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('finance-ledger'),
    tags: ['finance', 'three-band', 'balance-sheet', 'skill-bars'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: false,
    createdAt: '2025-07-21',
    component: lazy(() => import('./finance-ledger')),
  },

  'finance-portfolio': {
    id: 'finance-portfolio',
    name: 'Portfolio',
    description: 'Emulates an investment portfolio document. Modular grid of bordered section cards representing portfolio holdings. Accent header bar with metric badges (years, roles, certs). For portfolio managers, asset managers, and wealth advisors.',
    category: 'finance',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('finance-portfolio'),
    tags: ['finance', 'portfolio', 'card-grid', 'modular'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: false,
    createdAt: '2025-07-21',
    component: lazy(() => import('./finance-portfolio')),
  },

  'finance-treasury': {
    id: 'finance-treasury',
    name: 'Treasury',
    description: 'Inspired by a treasury bond document. Narrow 15% left margin column holds section labels like "covenant notes", with main content flowing on the right. Hairline dividers mimic a treasury term sheet. For treasurers, capital markets, and corporate finance professionals.',
    category: 'finance',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('finance-treasury'),
    tags: ['finance', 'treasury', 'margin-column', 'bond'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: false,
    createdAt: '2025-07-21',
    component: lazy(() => import('./finance-treasury')),
  },

  'finance-equity': {
    id: 'finance-equity',
    name: 'Equity',
    description: 'Modeled after an equity research report. Research header with ticker initials and rating badge. "Investment thesis" summary callout. Experience as company snapshots with a left accent border and date as a bold price label. For equity research analysts and investment analysts.',
    category: 'finance',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('finance-equity'),
    tags: ['finance', 'equity', 'research', 'analyst'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: false,
    createdAt: '2025-07-21',
    component: lazy(() => import('./finance-equity')),
  },

  'finance-vault': {
    id: 'finance-vault',
    name: 'Vault',
    description: 'Inspired by the security of a bank vault. Masonry-style section blocks with a thick 4px accent top border creating a bulletproof institutional feel. Compact header, dark accent footer anchor strip. For CROs, audit partners, compliance directors, and financial controllers.',
    category: 'finance',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('finance-vault'),
    tags: ['finance', 'vault', 'blocks', 'institutional'],
    isAtsOptimized: true,
    supportsAvatar: false,
    supportsTwoColumns: false,
    createdAt: '2025-07-21',
    component: lazy(() => import('./finance-vault')),
  },

  // ── Education Templates ─────────────────────────────────────────────────────

  'edu-academic-renaissance': {
    id: 'edu-academic-renaissance',
    name: 'Academic Renaissance',
    description: 'A premium, editorial-academic design inspired by university journals and scholarly proceedings. Features a distinctive vertical ruled margin with clean right-column content flow, drop-cap initials, and sophisticated serif display typography. Perfect for professors, researchers, and academic scholars who want a template that reflects serious academic discourse.',
    category: 'education',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('edu-academic-renaissance'),
    tags: ['education', 'academic', 'journal', 'research', 'serif'],
    isAtsOptimized: true,
    supportsAvatar: true,
    supportsTwoColumns: false,
    createdAt: '2026-07-23',
    component: lazy(() => import('./edu-academic-renaissance')),
  },
  'edu-faculty-ledger': {
    id: 'edu-faculty-ledger',
    name: 'Faculty Ledger',
    description: 'Elegant, institutional design structured like a university ledger book. Features wide ruled margins, clean grid sections, and academic document typography. Two-column layout evokes report cards and grade sheets. Premium serif headers with academic accent details. Ideal for school principals, department chairs, and academic administrators.',
    category: 'education',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('edu-faculty-ledger'),
    tags: ['education', 'ledger', 'institutional', 'grade-sheet', 'principal'],
    isAtsOptimized: true,
    supportsAvatar: true,
    supportsTwoColumns: true,
    createdAt: '2026-07-23',
    component: lazy(() => import('./edu-faculty-ledger')),
  },
  'edu-centered-curriculum': {
    id: 'edu-centered-curriculum',
    name: 'Centered Curriculum',
    description: 'Premium editorial layout that exudes academic gravitas. Features centered serif display typography, flowing magazine-style sections, and subtle parchment-like background with watermark. Structured academic rhythm with soft visual hierarchy. Perfect for lecturers, PhD candidates, and scholars seeking sophisticated presentation.',
    category: 'education',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('edu-centered-curriculum'),
    tags: ['education', 'centered', 'magazine', 'scholarly', 'parchment'],
    isAtsOptimized: true,
    supportsAvatar: true,
    supportsTwoColumns: false,
    createdAt: '2026-07-23',
    component: lazy(() => import('./edu-centered-curriculum')),
  },

  // ── Fresher Templates ───────────────────────────────────────────────────────

  'fresher-trail': {
    id: 'fresher-trail',
    name: 'Career Trail',
    description: 'A career-roadmap inspired design with a decorative winding trail path, warm coral and navy palette, and journey-marker section entries. Perfect for fresh graduates mapping their career journey — approachable, energetic, and visually distinctive.',
    category: 'fresher',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('fresher-trail'),
    tags: ['fresher', 'trail', 'roadmap', 'journey', 'approachable'],
    isAtsOptimized: true,
    supportsAvatar: true,
    supportsTwoColumns: false,
    createdAt: '2026-07-23',
    component: lazy(() => import('./fresher-trail')),
  },
  'fresher-canvas': {
    id: 'fresher-canvas',
    name: 'Studio Canvas',
    description: 'An art-gallery inspired design with floating section blocks, artistic accent splashes, and editorial typography. Generous whitespace and a curated exhibition-panel layout that makes limited experience feel abundant and high-value.',
    category: 'fresher',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('fresher-canvas'),
    tags: ['fresher', 'canvas', 'portfolio', 'artistic', 'editorial'],
    isAtsOptimized: true,
    supportsAvatar: true,
    supportsTwoColumns: false,
    createdAt: '2026-07-23',
    component: lazy(() => import('./fresher-canvas')),
  },
  'fresher-dash': {
    id: 'fresher-dash',
    name: 'Pulse Dash',
    description: 'A modern analytics-dashboard inspired layout with metric badges, widget-style panels, progress bars, and a charcoal/emerald palette. Built for tech-savvy fresh graduates who want to present themselves like a product dashboard — clean, data-driven, and modern.',
    category: 'fresher',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('fresher-dash'),
    tags: ['fresher', 'dashboard', 'analytics', 'metrics', 'tech'],
    isAtsOptimized: true,
    supportsAvatar: true,
    supportsTwoColumns: false,
    createdAt: '2026-07-23',
    component: lazy(() => import('./fresher-dash')),
  },
  'fresher-tile': {
    id: 'fresher-tile',
    name: 'Achievement Tile',
    description: 'An achievement-wall / modular-tile layout inspired by gaming accomplishment screens. Each section is a distinct tile with colored accent stripes, rounded corners, and subtle depth. Makes every entry feel like a valuable unlock — playful yet professional.',
    category: 'fresher',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('fresher-tile'),
    tags: ['fresher', 'tile', 'modular', 'game', 'playful'],
    isAtsOptimized: true,
    supportsAvatar: true,
    supportsTwoColumns: false,
    createdAt: '2026-07-23',
    component: lazy(() => import('./fresher-tile')),
  },
  'fresher-neon': {
    id: 'fresher-neon',
    name: 'Neon Pulse',
    description: 'A dark-theme, high-energy design with neon glow accents and a futuristic club/creator aesthetic. Glass-morphism panels float over a deep indigo grid with ambient glow orbs. Bold, dramatic, and unforgettable — for fresh graduates who refuse to blend in.',
    category: 'fresher',
    tier: 'free',
    previewImageUrl: getTemplatePreviewUrl('fresher-neon'),
    tags: ['fresher', 'neon', 'dark', 'glassmorphism', 'bold'],
    isAtsOptimized: true,
    supportsAvatar: true,
    supportsTwoColumns: false,
    createdAt: '2026-07-23',
    component: lazy(() => import('./fresher-neon')),
  },
}

export const DEFAULT_TEMPLATE_ID = 'classic-professional'

/**
 * Derived preview URL for a template. Mirrors the `template-previews` storage
 * bucket path (created by the DB migration) — drop a `<id>.png` there and the
 * template gains a real preview image with no code change.
 */
export function getTemplatePreviewUrl(id: string): string {
  return `/storage/v1/object/public/template-previews/${id}.png`
}

/** Returns the template list for the template browser */
export function getTemplateList() {
  return Object.values(templateRegistry)
}
